baseURL = "http://thelastgreentree.bitbucket.io"
languageCode = "en-us"
title = "The Last Green Tree"
theme = "hugo-book"
resourceDir = "build/resources"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10
  [languages.es]
    contentDir = 'content/es'
    languageName = 'Español'
    weight = 20

[params]
  BookTheme = 'light'
  BookLogo = 'logo.svg'
  BookRepo = 'https://github.com/thelastgreentree/thelastgreentree.github.io'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'
