baseURL = "https://github.com/thelastgreentree/thelastgreentree.github.io.git"
languageCode = "en-us"
title = "The Last Green Tree"
theme = "hugo-book"
resourceDir = "build/resources"
enableGitInfo = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10
  [languages.es]
    contentDir = 'content/es'
    languageName = 'Español'
    weight = 20

[params]
  BookTheme = 'light'
  BookLogo = 'logo/logo.svg'
  BookRepo = 'https://github.com/thelastgreentree/thelastgreentree.github.io'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true